version: "3"                         #version of docker compose 
services: 
  node-app:
    #container_name: test-axis
    image: mohamedyahiasadek/axis-docker  
    build: .
      # ports:
      # - "4000:4000"
    env_file:
      - ./.env    
    deploy:
      replicas: 4
      update_config:
        parallelism: 2                ### make roll update parallel 2 container then after 2 container
        delay: 10s                                                    #### take 10sec to restart container
      restart_policy:
        condition: on-failure
        delay: 5s

    depends_on:      ##depends_on mean don't make app container up if the mongodb container up first because if app container is up and mongodb does not up app container is fail
      - postgres
        # - redis     
        #  mongo:
        #   image: mongo
        #restart: always
        # volumes:
        #  - mongo-db:/data/db/            ##store all data of DB 
        # environment:
        #   MONGO_INITDB_ROOT_USERNAME: root
        #   MONGO_INITDB_ROOT_PASSWORD: example     
        # mongo-express:
        # image: mongo-express
        # restart: always
        #  ports:
        #    - 8081:8081
        # environment:
        #ME_CONFIG_MONGODB_ADMINUSERNAME: root
        #ME_CONFIG_MONGODB_ADMINPASSWORD: example
        #ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/      
        #depends_on:      ##Garanty  
        # - mongo    
        # - redis  
        # redis: 
        # image: redis    
  nginx:
    image: nginx:stable-alpine
    ports:
    - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf    
    depends_on:
      - postgres    
  postgres:
    image: postgres
    restart: always
    volumes:
      - postgres-db:/var/lib/postgresql/data           ##store all data of DB 
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example      
volumes:
  mongo-db:
  postgres-db:    
    ## Refrence:https://github.com/docker-library/docs/blob/master/postgres/README.md for postgress-path in container
    ## laravel.con/docs/9.x   laravel
