version: "3"                         #version of docker compose 
services: 
  node-app:
     build: 
       context: .
       target: development  
       args:
         - NODE_ENV=development
     volumes:                          #pending
      - ./src:/app/src:ro
     environment:
      - NODE_ENV=development
     command: npm run start
